networks:
  peas-dev:
    name: peas-dev
  chat-dev:
    name: chat-dev
    internal: true
  auth-dev:
    name: auth-dev
    internal: true
  matchmaking-dev:
    name: matchmaking-dev
    internal: true
  ai_game-dev:
    name: ai_game-dev
    internal: true
  game-dev:
    name: game-dev
    internal: true

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8443:8443"
    volumes:
      - ./nginx/www:/var/www/html
      - ./nginx/www/:/requirements/nginx/www/
    networks:
      - peas-dev
    depends_on:
      - chat
      - auth
      - matchmaking

  chat:
    container_name: chat
    build:
      context: ./chat
      dockerfile: Dockerfile.dev
    env_file:
      - ./conf/dev.env-chat
    ports:
      - "8000:8000"
    volumes:
      - ./chat/app:/app/
    networks:
      - chat-dev
      - peas-dev
    depends_on:
      chat-db-dev:
        condition: service_healthy
    environment:
      - REDIS_HOST=chat-redis
      - REDIS_PORT=6379

  chat-redis:
    container_name: chat-redis
    image: redis:6
    networks:
      - chat-dev
    volumes:
      - chat-redis-volume-dev:/data
    command:
      redis-server --save 60 1 --loglevel warning

  chat-db-dev:
    container_name: chat-db-dev
    image: postgres:14
    restart: on-failure
    volumes:
      - chat-db-volume-dev:/var/lib/postgresql/data
    env_file:
      - ./conf/dev.env-chat
    networks:
      - chat-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 5

  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    env_file:
      - ./conf/dev.env-auth
    volumes:
      - ./auth/app:/app/
      - ./nginx/www/:/requirements/nginx/www/
    ports:
      - "8001:8001"
    networks:
      - peas-dev
      - auth-dev
    depends_on:
      auth-db-dev:
        condition: service_healthy

  auth-db-dev:
    container_name: auth-db-dev
    image: postgres:14
    restart: on-failure
    volumes:
      - auth-db-volume-dev:/var/lib/postgresql/data
    env_file:
      - ./conf/dev.env-auth
    networks:
      - auth-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 5


  matchmaking:
    container_name: matchmaking
    build:
      context: ./matchmaking
      dockerfile: Dockerfile.dev
    env_file:
      - ./conf/dev.env-matchmaking
    volumes:
      - ./matchmaking/app:/app/
    networks:
      - peas-dev
      - matchmaking-dev
    ports:
      - "8002:8002"
    depends_on:
      matchmaking-db-dev:
        condition: service_healthy
    environment:
      - REDIS_HOST=matchmaking-redis
      - REDIS_PORT=6379

  matchmaking-db-dev:
    container_name: matchmaking-db-dev
    image: postgres:14
    restart: on-failure
    volumes:
      - matchmaking-db-volume-dev:/var/lib/postgresql/data
    env_file:
      - ./conf/dev.env-matchmaking
    networks:
      - peas-dev
      - matchmaking-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 5

  matchmaking-redis:
    container_name: matchmaking-redis
    image: redis:6
    networks:
      - matchmaking-dev
    volumes:
      - matchmaking-redis-volume-dev:/data
    command:
      redis-server --save 60 1 --loglevel warning

  ai_game:
    container_name: ai_game
    build: 
      context: ./ai_game
      dockerfile: Dockerfile.dev
    networks:
      - peas-dev
      - ai_game-dev
    volumes:
      - ./ai_game/app:/app/
    ports:
      - "8003:8003"
    environment:
      - REDIS_HOST=ai_game-redis
      - REDIS_PORT=6379

  ai_game_redis:
    container_name: ai_game_redis
    image: redis:6
    networks:
      - ai_game-dev
    volumes:
      - ai_game-redis-volume-dev:/data
    command:
      redis-server --save 60 1 --loglevel warning

  game:
    container_name: game
    build: 
      context: ./game
      dockerfile: Dockerfile.dev
    networks:
      - peas-dev
      - game-dev
    volumes:
      - ./game/app:/app/
    ports:
      - "8004:8004"
    environment:
      - REDIS_HOST=game-redis
      - REDIS_PORT=6379

  game-redis:
    container_name: game-redis
    image: redis:6
    networks:
      - game-dev
    volumes:
      - game-redis-volume-dev:/data
    command:
      redis-server --save 60 1 --loglevel warning

  match-redis:
    container_name: match-redis
    image: redis:6
    networks:
      - game-dev
      - matchmaking-dev
    volumes:
      - match-redis-volume-dev:/data
    command:
      redis-server --save 60 1 --loglevel warning

volumes:
  chat-db-volume-dev: {}
  auth-db-volume-dev: {}
  game-db-volume-dev: {}
  matchmaking-db-volume-dev: {}
  chat-redis-volume-dev: {}
  game-redis-volume-dev: {}
  matchmaking-redis-volume-dev: {}
  ai_game-redis-volume-dev: {}
  match-redis-volume-dev: {}