networks:
  peas:
    name: peas

services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    networks:
      - peas
  live_chat:
    build: ./chat
    networks:
      - peas
    ports:
      - "3336:3336"

