networks:
  peas:
    name: peas
  chat:
    name: chat
    internal: true
  auth:
    name: auth
    internal: true
  matchmaking:
    name: matchmaking
    internal: true
  ai_game:
    name: ai_game
    internal: true
  game:
    name: game
    internal: true

services:
  nginx:
    build: ./nginx
    ports:
      - "8443:8443"
    networks:
      - peas
    depends_on:
      - chat
      - auth
      - matchmaking
    volumes:
      - ./nginx/www:/var/www/html
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  chat:
    build: ./chat
    env_file:
      - ./conf/.env-chat
    expose:
      - "8000"
    networks:
      - chat
      - peas
    depends_on:
      chat-db:
        condition: service_healthy
      chat-redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=chat-redis
      - REDIS_PORT=6379
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  chat-redis:
    container_name: chat-redis
    image: redis:6
    networks:
      - chat
    volumes:
      - chat-redis-volume:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  chat-db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - chat-db-volume:/var/lib/postgresql/data
    env_file:
      - ./conf/.env-chat
    networks:
      - chat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  auth:
    build: ./auth
    env_file:
      - ./conf/.env-auth
    expose:
      - "8001"
    networks:
      - peas
      - auth
    depends_on:
      auth-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./nginx/www/:/requirements/nginx/www/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  auth-db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - auth-db-volume:/var/lib/postgresql/data
    env_file:
      - ./conf/.env-auth
    networks:
      - auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  matchmaking:
    build: ./matchmaking
    env_file:
      - ./conf/.env-matchmaking
    networks:
      - peas
      - matchmaking
    expose:
      - "8002"
    depends_on:
      chat-db:
        condition: service_healthy
      matchmaking-redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=matchmaking-redis
      - REDIS_PORT=6379
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  matchmaking-db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - matchmaking-db-volume:/var/lib/postgresql/data
    env_file:
      - ./conf/.env-matchmaking
    networks:
      - peas
      - matchmaking
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  matchmaking-redis:
    container_name: matchmaking-redis
    image: redis:6
    networks:
      - matchmaking
    volumes:
      - matchmaking-redis-volume:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ai_game:
    container_name: ai_game
    build: 
      context: ./ai_game
      dockerfile: Dockerfile
    networks:
      - peas
      - ai_game
    volumes:
      - ./ai_game/app:/app/
    expose:
      - "8003"
    depends_on:
      ai_game-redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=ai_game-redis
      - REDIS_PORT=6379
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ai_game-redis:
    container_name: ai_game-redis
    image: redis:6
    networks:
      - ai_game
    volumes:
      - ai_game-redis-volume:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  game:
    container_name: game
    build: 
      context: ./game
      dockerfile: Dockerfile
    networks:
      - peas
      - game
    volumes:
      - ./game/app:/app/
    expose:
      - "8004"
    depends_on:
      game-redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=game-redis
      - REDIS_PORT=6379
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  game-redis:
    container_name: game-redis
    image: redis:6
    networks:
      - game
    volumes:
      - game-redis-volume:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  match-redis:
    container_name: match-redis
    image: redis:6
    networks:
      - game
      - matchmaking
      - auth
    volumes:
      - match-redis-volume:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  chat-db-volume: {}
  auth-db-volume: {}
  game-db-volume: {}
  matchmaking-db-volume: {}
  chat-redis-volume: {}
  game-redis-volume: {}
  matchmaking-redis-volume: {}
  ai_game-redis-volume: {}
  match-redis-volume: {}